import * as THREE from 'three'
import type { ConstructionId } from './poolGeometry'

// Every material here is built from plain color/roughness/metalness values
// or a small procedurally-drawn canvas texture -- nothing is fetched from
// the network or generated by a model, so a given construction always
// looks exactly the same, forever, with zero chance of the kind of
// per-render drift the old AI pipeline had. `side: THREE.DoubleSide`
// everywhere is deliberate: it means the hand-built wall/floor/deck
// geometry never has to get triangle winding perfectly right to be
// visible from the camera (see the comment in poolGeometry.ts).

function createCanvas(size: number): { canvas: HTMLCanvasElement; ctx: CanvasRenderingContext2D } {
  const canvas = document.createElement('canvas')
  canvas.width = size
  canvas.height = size
  const ctx = canvas.getContext('2d')
  if (!ctx) throw new Error('2D canvas context unavailable')
  return { canvas, ctx }
}

function seededRandom(seed: number): () => number {
  let s = seed % 2147483647
  if (s <= 0) s += 2147483646
  return () => {
    s = (s * 16807) % 2147483647
    return (s - 1) / 2147483646
  }
}

// A soft speckled/pebbled texture -- used for concrete/gunite's pebble
// finish, and (with a lighter, greyer palette) for the poured-concrete
// deck around every inground pool.
//
// IMPORTANT: THREE.ShapeGeometry (and the hand-built wall strip) normalize
// UVs to a plain 0-1 range across the WHOLE surface regardless of its real
// footprint -- so a 256px canvas of fine speckles, left at the default
// repeat of (1, 1), gets stretched exactly once across an entire 30-50ft
// deck. At that scale every speckle anti-aliases down to nothing and the
// surface reads as a single flat, texture-less color, no matter how good
// the lighting is. `repeatX`/`repeatY` force it to actually tile at a
// scale where the speckles stay visible.
function createSpeckleTexture(baseColor: string, speckleColor: string, seed: number, repeatX: number, repeatY: number): THREE.CanvasTexture {
  const size = 256
  const { canvas, ctx } = createCanvas(size)
  ctx.fillStyle = baseColor
  ctx.fillRect(0, 0, size, size)
  const rand = seededRandom(seed)
  ctx.fillStyle = speckleColor
  for (let i = 0; i < 900; i++) {
    const x = rand() * size
    const y = rand() * size
    const r = 0.6 + rand() * 1.6
    ctx.globalAlpha = 0.25 + rand() * 0.35
    ctx.beginPath()
    ctx.arc(x, y, r, 0, Math.PI * 2)
    ctx.fill()
  }
  ctx.globalAlpha = 1
  const texture = new THREE.CanvasTexture(canvas)
  texture.wrapS = THREE.RepeatWrapping
  texture.wrapT = THREE.RepeatWrapping
  texture.repeat.set(repeatX, repeatY)
  texture.colorSpace = THREE.SRGBColorSpace
  return texture
}

// A subtle grid of seam lines -- vinyl liners are installed in panels with
// visible seams every few feet, which is the one visual cue that reads as
// "vinyl" rather than a plain painted surface. See the repeat note above --
// same reasoning, tuned looser since liner panels are meant to read as a
// handful of large sections rather than a fine tiled pattern.
function createLinerSeamTexture(): THREE.CanvasTexture {
  const size = 256
  const { canvas, ctx } = createCanvas(size)
  ctx.fillStyle = '#2f7fb8'
  ctx.fillRect(0, 0, size, size)
  ctx.strokeStyle = 'rgba(255,255,255,0.16)'
  ctx.lineWidth = 2
  const step = size / 4
  for (let i = 1; i < 4; i++) {
    ctx.beginPath()
    ctx.moveTo(i * step, 0)
    ctx.lineTo(i * step, size)
    ctx.stroke()
    ctx.beginPath()
    ctx.moveTo(0, i * step)
    ctx.lineTo(size, i * step)
    ctx.stroke()
  }
  const texture = new THREE.CanvasTexture(canvas)
  texture.wrapS = THREE.RepeatWrapping
  texture.wrapT = THREE.RepeatWrapping
  texture.repeat.set(8, 3)
  texture.colorSpace = THREE.SRGBColorSpace
  return texture
}

// A muted panel-seam pattern for an above-ground pool's resin/metal wall.
function createPanelTexture(): THREE.CanvasTexture {
  const size = 256
  const { canvas, ctx } = createCanvas(size)
  ctx.fillStyle = '#c7cdd3'
  ctx.fillRect(0, 0, size, size)
  ctx.strokeStyle = 'rgba(60,70,80,0.25)'
  ctx.lineWidth = 3
  const step = size / 6
  for (let i = 1; i < 6; i++) {
    ctx.beginPath()
    ctx.moveTo(i * step, 0)
    ctx.lineTo(i * step, size)
    ctx.stroke()
  }
  const texture = new THREE.CanvasTexture(canvas)
  texture.wrapS = THREE.RepeatWrapping
  texture.wrapT = THREE.RepeatWrapping
  texture.repeat.set(6, 2)
  texture.colorSpace = THREE.SRGBColorSpace
  return texture
}

let cachedMaterials: Partial<Record<ConstructionId, THREE.Material>> = {}
let cachedDeckMaterial: THREE.Material | null = null
let cachedWallMaterial: THREE.Material | null = null
let cachedWaterMaterial: THREE.Material | null = null

export function getConstructionMaterial(construction: ConstructionId): THREE.Material {
  const cached = cachedMaterials[construction]
  if (cached) return cached

  let material: THREE.Material
  switch (construction) {
    case 'fiberglass':
      // Smooth, glossy gel-coat -- a flat tuned color reads as fiberglass
      // on its own, no texture needed.
      material = new THREE.MeshPhysicalMaterial({
        color: '#4fb8dd',
        roughness: 0.12,
        metalness: 0.05,
        clearcoat: 1,
        clearcoatRoughness: 0.08,
        side: THREE.DoubleSide,
      })
      break
    case 'vinyl_liner':
      material = new THREE.MeshStandardMaterial({
        map: createLinerSeamTexture(),
        roughness: 0.55,
        metalness: 0,
        side: THREE.DoubleSide,
      })
      break
    case 'concrete_gunite':
      material = new THREE.MeshStandardMaterial({
        map: createSpeckleTexture('#5b6b74', '#38464e', 7, 10, 6),
        roughness: 0.85,
        metalness: 0,
        side: THREE.DoubleSide,
      })
      break
  }
  cachedMaterials[construction] = material
  return material
}

export function getDeckMaterial(): THREE.Material {
  if (cachedDeckMaterial) return cachedDeckMaterial
  cachedDeckMaterial = new THREE.MeshStandardMaterial({
    map: createSpeckleTexture('#d9d5cc', '#b8b2a4', 3, 16, 16),
    roughness: 0.9,
    metalness: 0,
    side: THREE.DoubleSide,
  })
  return cachedDeckMaterial
}

export function getAboveGroundWallMaterial(): THREE.Material {
  if (cachedWallMaterial) return cachedWallMaterial
  cachedWallMaterial = new THREE.MeshStandardMaterial({
    map: createPanelTexture(),
    roughness: 0.6,
    metalness: 0.15,
    side: THREE.DoubleSide,
  })
  return cachedWallMaterial
}

export function getWaterMaterial(): THREE.Material {
  if (cachedWaterMaterial) return cachedWaterMaterial
  cachedWaterMaterial = new THREE.MeshPhysicalMaterial({
    color: '#4fc3e8',
    transparent: true,
    opacity: 0.82,
    roughness: 0.05,
    metalness: 0,
    transmission: 0.35,
    thickness: 1.5,
    side: THREE.DoubleSide,
  })
  return cachedWaterMaterial
}

export function getCoverMaterial(cover: string): THREE.Material {
  const colorByCover: Record<string, string> = {
    manual: '#2f6fb0',
    automatic: '#37424c',
    safety_cover: '#2f7a4d',
  }
  return new THREE.MeshStandardMaterial({
    color: colorByCover[cover] ?? '#2f6fb0',
    roughness: 0.75,
    metalness: 0,
    side: THREE.DoubleSide,
  })
}
